# Generated by Django 4.0 on 2022-09-11 16:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookISBN', models.IntegerField(primary_key=True, serialize=False)),
                ('BookTitle', models.CharField(max_length=150)),
                ('BookAuthor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Issued',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentRoll', models.IntegerField()),
                ('IssueDate', models.DateField(default=datetime.date(2022, 9, 11))),
                ('DueDate', models.DateField(default=datetime.date(2022, 9, 26))),
                ('BookISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
            ],
        ),
    ]
